version: '3'
services:
  redis:
    image: 'redis:latest'
  nginx:
    restart: always
    build:
      dockerfile: Dockerfile.dev
      context: ./nginx
    ports:
      - '80:80'
  api:
    depends_on:
      - redis
    build:
      context: ./server
      dockerfile: Dockerfile.dev
    volumes:
      - /app/node_modules
      - ./server:/app
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
  socket:
    depends_on:
      - redis
    build:
      context: ./socket
      dockerfile: Dockerfile.dev
    volumes:
      - /app/node_modules
      - ./socket:/app
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
  # client:
  #   stdin_open: true
  #   build:
  #     dockerfile: Dockerfile.dev
  #     context: ./client
  #   volumes:
  #     - /app/node_modules
  #     - ./client:/app